= OpenRecipeBook

One of the best things about open source is its collaborative nature and the sense of community that it creates. For a lot of projects however, finding new contributors can be difficult since many users don't have the inclination to code, and writing high quality documentation can be very difficult. This project hopes to occupy a niche where contributing documentation through open source can be fun and easy, because anybody can cook and recipes can be fun to share!

== Building

=== Ubuntu

....
$ sudo apt install --assume-yes make pandoc python3-pip ruby
$ sudo gem install bundler
$ pip3 install --user -r requirements.txt
$ bundle install
$ make
$ xdg-open builds/recipe-book.pdf
....

=== Fedora/Silverblue

....
$ toolbox create --container openrecipebook --release f31
$ toolbox run --container openrecipebook sudo dnf --assumeyes install make pandoc python3-pip ruby
$ toolbox run --container openrecipebook sudo gem install bundler
$ toolbox run --container openrecipebook pip3 install --user -r requirements.txt
$ toolbox run --container openrecipebook bundle install
$ toolbox run --container openrecipebook make
$ xdg-open builds/recipe-book.pdf
....

=== OpenSUSE

....
$ sudo zypper --non-interactive install make pandoc python3-pip ruby
$ sudo gem install bundler
$ pip3 install --user -r requirements.txt
$ bundle install
$ make
$ xdg-open builds/recipes-book.pdf
....

== Community

Please check out the official https://discord.gg/sDzCaeH[OpenRecipeBook Discord server]! On there you can discuss ways to improve OpenRecipeBook, make suggestions for recipes, recommend cooking tips, etc.

== Contributing a recipe

Anyone is welcome to contribute a recipe that they've perfected over time and have wanted to share with others! Please note that some guidelines should be followed for a consistent reading experience:

- Additions should be derived from `src/templates/`. Recipes are stored as YAML, which can be checked by running `src/bin/checkschema.py`.
- Equipment should be explicitely listed, and any equipment should link to the equipment section of the recipe book. This lets aspiring home chefs quickly understand what they'd need to start cooking
- Equipment additions should be anything contributors have personally used and would recommend and/or are well-reviewed by reputable sources
- Measurements should use mass whenever possible. Due to differences and inconsistencies in measuring systems, measuring by volume can lead to an otherwise good recipe having poor results.
- Measurements using whole units, e.g., "1 tomato", are acceptable as they're often intuitive to read. Listing mass alongside for accuracy is recommended as well
- Mentioning brands is helpful since there tends to be deviation in taste, texture, etc.

== TODO

- Port more of the project to YAML
- Set up CI
- Adding wiki pages
- Support converting between mass Imperial and Metric
- Look into supporting images
