[[bloody-ceasar]]
=== Bloody Ceasar

Yield: 1 drink

Equipment:

* <<cocktail-shakers, Cocktail Shaker>>
* <<highball-glasses, Highball Glass>>
* <<japanese-jigger, Jigger>>
* Cocktail spear
* Straw

Ingredients:

* 1.5oz of Vodka (or Gin)
* 4.5oz of Clamato juice
* 0.75oz of Fresh lemon juice
* Lemon wedge
* Salt and Black pepper (or Steak spice)
* 1 tsp. of Tabasco hot sauce
* 1 tsp. of Cholula hot sauce
* 1 tsp. of Worcestershire sauce
* Pickled green bean (or celery stick)
* 3 Mini dill pickles

Steps:

. Slide a lemon wedge around the edge of the highball glass, coating 1-2cm of the outer edge in juice.
. Add equal parts salt and black pepper to a plate. Roll edge of glass over the mix to rim the glass.
. Crush ice into the highball glass, and place into a freezer or icebox to chill.
. Combine vodka, clamato juice, lemon juice, hot sauces, and Worcestershire sauce in the cocktail shaker.
. (Optional) Add a dash of salt and black pepper to the shaker to taste.
. Add one large ice cube and one scrushed ice cube to the shaker. Shake vigourously.
. Strain into a chilled, ice-filled highball glass.
. Insert 1-2 pickled green beans into the drink (to taste).
. Skewer three mini dill pickles onto the cocktail spear. Balance spear on rim of glass as garnish.
. Squeeze the lemon wedge over the drink, then drop it in.
  NOTE: Alternatively, notch the wedge onto the edge of the glass.
